### ISSUE TITLE
Mesh of "storm_merc_wintercrest_boss.m3" won't import

### ISSUE THREAD

**Issue by DerekX** [Talv/m3addon#43]
I get this error when trying to import the Headless Horseman from Heroes of the Storm:

Python: Traceback (most recent call last):
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\m3addon-master\ui\base.py", line 155, in execute
    m3import.importM3BasedOnM3ImportOptions(scene)
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\m3addon-master\m3import.py", line 1957, in importM3BasedOnM3ImportOptions
    importer.importM3BasedOnM3ImportOptions(scene)
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\m3addon-master\m3import.py", line 478, in importM3BasedOnM3ImportOptions
    self.createMaterials()
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\m3addon-master\m3import.py", line 831, in createMaterials
    transferMethod(materialTransferer)
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\m3addon-master\shared.py", line 1947, in transferStandardMaterial
    transferer.transferEnum("blendMode")
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\m3addon-master\m3import.py", line 423, in transferEnum
    setattr(self.blenderObject, fieldName, value)
TypeError: bpy_struct: item.attr = val: enum "7" not found in ('0', '1', '2', '3', '4', '5', '6')

location: <unknown location>:-1

**Comment by Solstice245** [comment]
Have you updated to the latest version of the addon? I do believe this problem was addressed a few commits ago.

**Comment by DerekX** [comment]
No but I don't think I'm so far behind the latest update. I last updated at the beginning of this year. I couldn't imagine that issue would be fixed with the latest version, but I'll take a look at stuff.

**Comment by DerekX** [comment]
Why did I doubt updating? Just updated to the latest version and the mesh of the Headless Horseman imports. :)

**Comment by Solstice245** [comment]
Yep. Just as a general rule, you should always update to the latest version of a branch before reporting issues for it.
